[dependencies]
hyper = "0.14"
ruma = { git = "https://github.com/ruma/ruma", features = [
    "client",
    "client-api",
] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.5"
